import AppKit
import ImageIO
import ColCore
import Observation

/// Remembers recent text copies, in memory only: only the texts the user pins are saved, in the preferences, and copies
/// that password managers mark as concealed or transient are skipped.
@MainActor
@Observable
final class ClipboardMonitor {
    private(set) var history = ClipboardHistory()
    /// Full-size data of image copies, by entry, so a copy goes back at its real size. Memory only, and bounded.
    @ObservationIgnored private var originals: [UUID: (data: Data, type: NSPasteboard.PasteboardType)] = [:]
    @ObservationIgnored private var timer: Timer?
    @ObservationIgnored private var running = false
    /// True while demo copies stand in for the user's: the pasteboard is neither read nor written, nothing is saved.
    @ObservationIgnored private var demo = false
    private static let pinsKey = "pinnedClipboard"
    private static let originalsBudget = 40 << 20
    @ObservationIgnored private var lastChange = NSPasteboard.general.changeCount

    /// Markers from nspasteboard.org that password managers and similar apps set on sensitive copies.
    private static let privateTypes: Set<String> = [
        "org.nspasteboard.ConcealedType",
        "org.nspasteboard.TransientType",
        "org.nspasteboard.AutoGeneratedType",
        "com.agilebits.onepassword",
        "de.petermaurer.TransientPasteboardType",
    ]

    func start() {
        guard !running, Preferences.keepsClipboardHistory else { return }
        history.restorePinned(UserDefaults.standard.stringArray(forKey: Self.pinsKey) ?? [])
        running = true
        scheduleCheck()
    }

    /// The pasteboard has no change notification: one counter is read, every 2 seconds while you use the Mac and
    /// less often while it sits idle (`ClipboardPolling`), with a generous tolerance so the system can batch the
    /// wake-up with others.
    private func scheduleCheck() {
        guard running else { return }
        let idle = CGEventSource.secondsSinceLastEventType(.combinedSessionState, eventType: CGEventType(rawValue: ~0) ?? .keyDown)
        let interval = ClipboardPolling.interval(secondsSinceInput: idle)
        let timer = Timer(timeInterval: interval, repeats: false) { [weak self] _ in
            MainActor.assumeIsolated {
                self?.check()
                self?.scheduleCheck()
            }
        }
        timer.tolerance = interval / 2
        RunLoop.main.add(timer, forMode: .common)
        self.timer = timer
    }

    func stop() {
        running = false
        timer?.invalidate()
        timer = nil
        history.clear()
        originals.removeAll()
    }

    func check() {
        guard !demo else { return }
        let pasteboard = NSPasteboard.general
        guard pasteboard.changeCount != lastChange else { return }
        lastChange = pasteboard.changeCount
        let types = Set((pasteboard.types ?? []).map(\.rawValue))
        guard types.isDisjoint(with: Self.privateTypes) else { return }
        let app = NSWorkspace.shared.frontmostApplication?.localizedName
        if let text = pasteboard.string(forType: .string) {
            history.add(text, at: Date(), from: app)
        } else if let (data, type) = [NSPasteboard.PasteboardType.png, .tiff].lazy.compactMap({ type in pasteboard.data(forType: type).map { ($0, type) } }).first,
                  let thumbnail = Self.thumbnail(of: data) {
            history.add(image: thumbnail.png, label: thumbnail.label, at: Date(), from: app)
            if let id = history.entries.first?.id { keepOriginal(data, type: type, for: id) }
        }
    }

    private func keepOriginal(_ data: Data, type: NSPasteboard.PasteboardType, for id: UUID) {
        originals[id] = (data, type)
        let alive = Set(history.entries.map(\.id))
        originals = originals.filter { alive.contains($0.key) }
        // Drop the oldest originals past the budget; their thumbnails stay.
        var total = 0
        for entry in history.entries where originals[entry.id] != nil {
            total += originals[entry.id]!.data.count
            if total > Self.originalsBudget { originals[entry.id] = nil }
        }
    }

    /// A small PNG for the list, and a label with the real size.
    private static func thumbnail(of data: Data) -> (png: Data, label: String)? {
        guard let source = CGImageSourceCreateWithData(data as CFData, nil),
              let properties = CGImageSourceCopyPropertiesAtIndex(source, 0, nil) as? [CFString: Any],
              let width = properties[kCGImagePropertyPixelWidth] as? Int,
              let height = properties[kCGImagePropertyPixelHeight] as? Int,
              let image = CGImageSourceCreateThumbnailAtIndex(source, 0, [
                  kCGImageSourceCreateThumbnailFromImageAlways: true,
                  kCGImageSourceThumbnailMaxPixelSize: 160,
                  kCGImageSourceCreateThumbnailWithTransform: true,
              ] as CFDictionary),
              let png = NSBitmapImageRep(cgImage: image).representation(using: .png, properties: [:])
        else { return nil }
        return (png, String(localized: "Image \(width) × \(height)", bundle: .module))
    }

    func togglePin(_ entry: ClipboardHistory.Entry) {
        history.togglePin(entry.id)
        if !demo { UserDefaults.standard.set(history.pinnedTexts, forKey: Self.pinsKey) }
    }

    /// For screenshots: a few ordinary copies stand in for the user's history, which is never read. `image` is the
    /// picture of the copied photo.
    func showDemo(image: Data?) {
        demo = true
        running = false
        timer?.invalidate()
        timer = nil
        history.clear()
        originals.removeAll()
        let now = Date()
        history.add("Meet at 7, same place as last time?", at: now.addingTimeInterval(-600), from: "Messages")
        if let image, let thumbnail = Self.thumbnail(of: image) {
            history.add(image: thumbnail.png, label: thumbnail.label, at: now.addingTimeInterval(-300), from: "Photos")
        }
        history.add("The notch, made useful.", at: now, from: "TextEdit")
    }

    /// Puts an entry back on the clipboard, ready to paste.
    func copy(_ entry: ClipboardHistory.Entry) {
        guard !demo else { return }
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        if entry.isImage {
            if let original = originals[entry.id] {
                pasteboard.setData(original.data, forType: original.type)
            } else if let image = entry.image {
                pasteboard.setData(image, forType: .png)
            }
        } else {
            pasteboard.setString(entry.text, forType: .string)
            history.add(entry.text, at: Date(), from: entry.sourceApp)
        }
        lastChange = pasteboard.changeCount
    }

    func remove(_ entry: ClipboardHistory.Entry) {
        history.remove(entry.id)
        originals[entry.id] = nil
        if entry.pinned, !demo { UserDefaults.standard.set(history.pinnedTexts, forKey: Self.pinsKey) }
    }

    func clear() {
        history.clear()
    }
}
